[font]
normal = { family = "JetBrains Mono NL", style = "Light" }
bold = { style = "Regular" }
size = 15.5
# offset = { y = 5, x = 0 }

[cursor]
# style = { blinking = "On", shape = "Block" }
vi_mode_style = { blinking = "Off", shape = "Block" }

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"
padding = { x = 5, y = 5 }
dynamic_padding = true
startup_mode = "Maximized"

[scrolling]
history = 100000


# Colors (Alabaster)

[colors.primary]
background = '#FFFFFF'
foreground = '#000000'

[colors.cursor]
text = '#F7F7F7'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'
