[directory]
truncate_to_repo = false
style = "#00839e"
repo_root_style = "bold 39"
truncation_length = 6
truncation_symbol = "../"

[character]
success_symbol = "[ᐅ](bold green)"
error_symbol = "[ᐅ](bold red)"
vicmd_symbol = "[ᐊ](bold blue)"

[git_branch]
style = "bg:193 green"
symbol = ""
format = "[ $symbol $branch(:$remote_branch) ]($style) "

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[git_status]
stashed = ""
style = "bold yellow"

[package]
symbol = ""
style = "208"

[nodejs]
symbol = "nodejs "
version_format = "v${major}"
style = "green"
