command_timeout = 5000

[directory]
truncate_to_repo = false
style = "#00839e"
repo_root_style = "bold 39"
truncation_length = 6
truncation_symbol = "../"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold blue)"

[git_branch]
style = "bg:193 green"
format = "[ $symbol $branch(:$remote_branch) ]($style) "

[git_metrics]
disabled = true
added_style = "green"
deleted_style = "red"

[git_status]
stashed = ""
style = "bold yellow"

[package]
symbol = ""
style = "208"

[nodejs]
version_format = "v${major}"
style = "green"

