[directory]
truncate_to_repo = false
style = "#00839e"
repo_root_style = "bold 39"
truncation_length = 6
truncation_symbol = "../"

[git_branch]
style = "green"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[git_status]
stashed = ""
style = "bold yellow"

[nodejs]
symbol = "nodejs "
version_format = "v${major}"
style = "green"
